name: ivqa
channels:
  - pytorch
  - nvidia
  - xformers
  - defaults
dependencies:
  - python=3.10.14
  - pip=24.0.0
  - pytorch-cuda=11.8
  - pytorch=2.2.0
  - torchvision=0.17.0
  - xformers=0.0.24
  - pip:
    - lightning==2.2.0
    - torchmetrics==1.3.0
    - transformers==4.36.2
    - diffusers==0.25.0
    - accelerate==0.25.0
    - triton==2.3.1
    - einops==0.8.0
    - kornia==0.7.3
    - timm==1.0.7
    - opencv-python==4.9.0.80
    - numpy==1.26.2
    - scikit-learn==1.3.2
    - scipy==1.11.1
    - albumentations==1.3.1
    - imageio==2.34.2
    - imageio-ffmpeg==0.5.1
    - decord==0.6.0
    - av==12.2.0
    - invisible-watermark==0.2.0
    - jupyterlab==4.2.3
    - omegaconf==2.3.0
    - fire==0.6.0
    - matplotlib==3.9.1
    - seaborn==0.13.2
    - piq==0.8.0
    - lpips==0.1.4
    - wandb==0.17.4
    - tqdm==4.66.4
    - prettytable==3.10.0
    - openpyxl==3.1.5
    - -e git+https://github.com/CompVis/taming-transformers.git@master#egg=taming-transformers
    - -e git+https://github.com/openai/CLIP.git@main#egg=clip
    - -e git+https://github.com/SimonRaviv/CV-VAE.git@main#egg=cv-vae
    - -e .
