name: ldm
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.8.10
  - pip=20.3
  - cudatoolkit=11.3
  - pytorch=1.12.1
  - torchvision=0.13.1
  - numpy=1.22.3
  - pip:
    - ipykernel==6.23.1
    - ipython==8.12.2
    - ipython-genutils==0.2.0
    - jupyter == 1.0.0
    - jupyterlab==4.0.5
    - ipywidgets==8.0.6
    - lightning==2.0.6
    - lightning-cloud==0.5.37
    - lightning-utilities==0.9.0
    - pytorch-lightning==2.0.6
    - torchmetrics==1.0.2
    - torchvision==0.14.1
    - torcheval==0.0.6
    - torchview==0.2.6
    - torch-fidelity==0.3.0
    - piq==0.8.0
    - diffusers==0.13.1
    - humanfriendly==10.0
    - invisible-watermark==0.1.5
    - coloredlogs==15.0.1
    - mpmath==1.2.1
    - onnx==1.13.1
    - onnxruntime==1.14.0
    - open-clip-torch==2.14.0
    - safetensors==0.2.8
    - sentencepiece==0.1.97
    - sympy==1.11.1
    - timm==0.6.12
    - accelerate==0.16.0
    - albumentations==1.1.0
    - opencv-python==4.2.0.34
    - pudb==2019.2
    - imageio==2.14.1
    - imageio-ffmpeg==0.4.7
    - omegaconf==2.1.1
    - test-tube>=0.7.5
    - streamlit>=0.73.1
    - setuptools==59.5.0
    - pillow==9.0.1
    - einops==0.4.1
    - transformers==4.29.2
    - kornia==0.6
    - matplotlib==3.7.0
    - scikit-learn==1.2.0
    - scipy==1.10.1
    - wandb==0.15.11
    - tqdm==4.65.0
    - seaborn==0.12.2
    - prettytable==3.6.0
    - graphviz==0.20.1
    - xformers
    - triton
    - -e git+https://github.com/CompVis/taming-transformers.git@master#egg=taming-transformers
    - -e git+https://github.com/openai/CLIP.git@main#egg=clip
    - -e .
